### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by VinSpee** [diecodev/qwik-sonner#12]
Killer work on this. Thank you for doing it.

Any thoughts on porting https://github.com/emilkowalski/vaul too? IMO those are the two pieces missing in order to make a real shadcn/ui port for Qwik which I think would have an immense impact on the community.

**Comment by diecodev** [comment]
Thank you for the compliment!

As far as I know from my conversation with Jack Shelton (@thejackshelton), someone is already working on creating the Qwik version of Vaul. Right now, I’m focused on developing the Qwik-UI Calendar, as well as an opinionated version of it to resemble something like shadcn/calendar.

However, if the Vaul port hasn't been created by the time I finish with the calendar, I’d be happy to take it on.

**Comment by VinSpee** [comment]
awesome to hear. Thanks again!

**Comment by thejackshelton** [comment]
Hey @VinSpee. To my knowledge this isn't being worked on, not sure what @diecodev is referring to here.

That said, we would love to have something similar in Qwik UI styled (this would be part of the modal or drawer component), contributions welcome 👍
