### ISSUE TITLE
It would be good to add progress bar

### ISSUE THREAD

**Issue by notcod** [diecodev/qwik-sonner#5]
![image](https://github.com/diecodev/qwik-sonner/assets/77313746/7c75e80c-cb0f-4f29-b6d7-0331352eddda)

**Comment by diecodev** [comment]
Hi, thanks for the issue.

I don't think your proposal is in line with the default Toast design. However, it would be helpful if you could create a design in figma or similar where you use the default toast and add the progress bar, to see how it looks and make a final decision. 

> [!NOTE]
> Btw, if you want to implement this exact design, you can use the toast.custom() function.

**Comment by notcod** [comment]
![image](https://github.com/diecodev/qwik-sonner/assets/77313746/1cb7edb3-bbd2-4145-a546-55356049dfb7)
![image](https://github.com/diecodev/qwik-sonner/assets/77313746/1fafe479-4bbf-49f5-bf1f-527ef19d9a97)

 My prettier config fuck up code with a lot of changes, but here is git https://github.com/notcod/qwik-sonner/commits/main/
 If I get time tomorrow I will re-make it and push clean code if you like idea
 
```
export interface ToastProps {
  /// ...rest
  progressBar?: boolean;
  progressBarColor?: string;
}

interface ToastOptions {
  /// ...rest
  progressBar?: boolean;
  progressBarColor?: string;
}
export const Toast = component$((props: ToastProps) => {
  const percent = useSignal(100);
  useStyles$(`
    .pre-loading{
      position: absolute;
      bottom: 0;
      left: 0;
      width: 100%;
      height: 5px;
      background: #f2f2f2;
      border-radius: 0 0 5px 5px;
    }
    .loading{
      width: 100%;
      height: 5px;
      width: 0;
      transition: width 0.5s;
      border-radius: 0 0 0 5px; 
    }
  `);
  ///// ...rest

  let timeoutId: number;
  const startTimer = () => {
    ///// ...rest

    intervalId = setInterval(() => {
        const elapsedTime = new Date().getTime() - closeTimerStartTimeRef.value;
        percent.value = (0.98 - elapsedTime / duration.value) * 100;
      }, duration.value / 50);
  };

  cleanup(() => clearTimeout(intervalId));
  ///// ...rest
  return (
    /// ...rest
        {props.progressBar && (
          <div class="pre-loading">
            <div class="loading" style={` width:${percent.value}%; background: ${props.progressBarColor || 'black'}`} />
          </div>
        )}
      </Fragment>
    )}
    </li>
  );
});




export const Toaster = component$<ToasterProps>((props) => {
  /// ...rest
  return (
    <Toast
    /// ...rest
    progressBar={toastOptions?.progressBar}
    progressBarColor={toastOptions?.progressBarColor}
  /// ...rest

```

**Comment by notcod** [comment]
![image](https://github.com/diecodev/qwik-sonner/assets/77313746/22da300d-6f38-4976-aade-a81246026586)
First one is https://fkhadra.github.io/react-toastify/introduction
second one is sonner with config:
![image](https://github.com/diecodev/qwik-sonner/assets/77313746/c36975b4-74be-4f09-aeed-70a3cc23e61d)
I think I achieve my goal, I was using react integration in my project but I think I can move my project to this one, I would like to change toast drag to left right instead of current just to up, how I can make it?

**Comment by diecodev** [comment]
hey @notcod gj, mate. What should I do for you? Wdyt about create a custom stylesheet for the component?

**Comment by notcod** [comment]
I edited it to satisfy my project needs, but didn't get time to push clean commits to your repository. I just uploaded test site and realised that toast works only when page accessed via spa Link.... I will take a look at this problem tomorrow, probably the reason is useTask$, but will confirm latter.
check it https://fc52ca83.qwik-toastify.pages.dev/
updated icons and colors, shuffled your code a little, probably messed up default things but got what I needed, here is code https://github.com/notcod/toastify
Btw, I learned few things from your code, you are really experienced in the field 
![image](https://github.com/diecodev/qwik-sonner/assets/77313746/b8cc7cd0-e691-4227-a18c-1c432bc572c5)

**Comment by notcod** [comment]
I made it able to swipe left/right instead of default up/down, also dismisable by clicking on it, maybe you should put it as optional? I can commit feature you want to your code, which one would you like?

**Comment by diecodev** [comment]
Hey @notcod, pls create a PR to make the toast dismissible for left/right. 

As for your proposed new design, I regret to inform you that after talking with my partner (@devalexpy), we consider that it does not go according to [`sonner` design](https://sonner.emilkowal.ski/) (the original version based on react) so we do not consider good idea to implement your proposed one. However, I am glad to know that you were able to adapt `qwik-sonner` to your needs.

**Comment by diecodev** [comment]
going to close this issue for now. If you think this should be reopened pls do it. 😄
