### ISSUE TITLE
Theme doesn't changes

### ISSUE THREAD

**Issue by Wykks** [diecodev/qwik-sonner#7]
Hi!

Awesome library! I was playing around with it, and noticed that the `theme` prop is read only once. In most website supporting dark mode, it's something you want to change at runtime. Can you support dynamic changes to the prop `theme` ?

**Comment by diecodev** [comment]
Thanks for the PR. I will fix it today and then ping you to let you know, so you can update.

**Comment by diecodev** [comment]
this is solved in the last version, pls check it out upgrading the library and lmk if something else is bugged. Thank you again for the PR

**Comment by Wykks** [comment]
Works perfectly thanks ! :smiley:
